import type { Transaction } from "./types";

export const transactions: Transaction[] = [
  {
    id: "tx-001",
    date: "2026-01-08",
    client: "Clínica Atlântico",
    category: "Software à medida",
    description: "Módulo de marcações e faturação",
    amount: 4200,
    type: "income",
    channel: "Parceiro",
  },
  {
    id: "tx-002",
    date: "2026-01-15",
    client: "CloudHost EU",
    category: "Infraestrutura",
    description: "Servidores, logs e backups",
    amount: 640,
    type: "expense",
    channel: "Recorrente",
  },
  {
    id: "tx-003",
    date: "2026-02-03",
    client: "Madeira Homes",
    category: "Portal cliente",
    description: "Entrega inicial de portal imobiliário",
    amount: 5100,
    type: "income",
    channel: "Online",
  },
  {
    id: "tx-004",
    date: "2026-02-18",
    client: "Ads Manager",
    category: "Marketing",
    description: "Campanhas de captação de leads",
    amount: 980,
    type: "expense",
    channel: "Online",
  },
  {
    id: "tx-005",
    date: "2026-03-06",
    client: "FormaPro Academy",
    category: "Dashboard BI",
    description: "Relatórios de alunos e pagamentos",
    amount: 3600,
    type: "income",
    channel: "Parceiro",
  },
  {
    id: "tx-006",
    date: "2026-03-21",
    client: "Design Studio",
    category: "Serviços externos",
    description: "Identidade visual e UI kit",
    amount: 1200,
    type: "expense",
    channel: "Parceiro",
  },
  {
    id: "tx-007",
    date: "2026-04-04",
    client: "Solar Norte",
    category: "Integrações",
    description: "Integração CRM e ERP",
    amount: 6800,
    type: "income",
    channel: "Online",
  },
  {
    id: "tx-008",
    date: "2026-04-19",
    client: "Tools Suite",
    category: "Subscrições",
    description: "Ferramentas de desenvolvimento",
    amount: 420,
    type: "expense",
    channel: "Recorrente",
  },
  {
    id: "tx-009",
    date: "2026-05-02",
    client: "Vila Verde Tours",
    category: "Sistema de reservas",
    description: "Reservas, vouchers e pagamentos",
    amount: 4100,
    type: "income",
    channel: "Loja",
  },
  {
    id: "tx-010",
    date: "2026-05-16",
    client: "Freelance Ops",
    category: "Serviços externos",
    description: "Apoio QA e documentação",
    amount: 760,
    type: "expense",
    channel: "Parceiro",
  },
  {
    id: "tx-011",
    date: "2026-06-07",
    client: "Restaurante Baía",
    category: "Website + automação",
    description: "Landing page e funil de reservas",
    amount: 2300,
    type: "income",
    channel: "Parceiro",
  },
  {
    id: "tx-012",
    date: "2026-06-12",
    client: "Cowork Madeira",
    category: "Operações",
    description: "Sala, internet e material",
    amount: 530,
    type: "expense",
    channel: "Recorrente",
  },
  {
    id: "tx-013",
    date: "2026-07-03",
    client: "Contas & Gestão",
    category: "Dashboard BI",
    description: "Controlo financeiro e exportações",
    amount: 5200,
    type: "income",
    channel: "Online",
  },
  {
    id: "tx-014",
    date: "2026-07-22",
    client: "CloudHost EU",
    category: "Infraestrutura",
    description: "Ambientes staging e produção",
    amount: 710,
    type: "expense",
    channel: "Recorrente",
  },
  {
    id: "tx-015",
    date: "2026-08-09",
    client: "Oficina Central",
    category: "Agenda operacional",
    description: "Agenda, clientes e avisos",
    amount: 3100,
    type: "income",
    channel: "Loja",
  },
  {
    id: "tx-016",
    date: "2026-08-27",
    client: "Ads Manager",
    category: "Marketing",
    description: "Campanhas LinkedIn e Google",
    amount: 1120,
    type: "expense",
    channel: "Online",
  },
  {
    id: "tx-017",
    date: "2026-09-05",
    client: "Norte Digital",
    category: "CRM comercial",
    description: "Pipeline, leads e relatórios",
    amount: 4700,
    type: "income",
    channel: "Parceiro",
  },
  {
    id: "tx-018",
    date: "2026-09-19",
    client: "Legal Partner",
    category: "Portal cliente",
    description: "Pedidos, documentos e estados",
    amount: 5900,
    type: "income",
    channel: "Online",
  },
  {
    id: "tx-019",
    date: "2026-10-11",
    client: "Design Studio",
    category: "Serviços externos",
    description: "UX audit e prototipagem",
    amount: 1450,
    type: "expense",
    channel: "Parceiro",
  },
  {
    id: "tx-020",
    date: "2026-10-23",
    client: "Mar Azul Retail",
    category: "E-commerce",
    description: "Catálogo, checkout e backoffice",
    amount: 7400,
    type: "income",
    channel: "Online",
  },
  {
    id: "tx-021",
    date: "2026-11-04",
    client: "Travel Desk",
    category: "Integrações",
    description: "Integração com pagamentos e CRM",
    amount: 3800,
    type: "income",
    channel: "Parceiro",
  },
  {
    id: "tx-022",
    date: "2026-11-20",
    client: "Tools Suite",
    category: "Subscrições",
    description: "Analytics, email e monitorização",
    amount: 560,
    type: "expense",
    channel: "Recorrente",
  },
  {
    id: "tx-023",
    date: "2026-12-06",
    client: "Health Plus",
    category: "Software à medida",
    description: "Backoffice multi-unidade",
    amount: 8200,
    type: "income",
    channel: "Online",
  },
  {
    id: "tx-024",
    date: "2026-12-18",
    client: "Freelance Ops",
    category: "Serviços externos",
    description: "Apoio a migração de dados",
    amount: 1350,
    type: "expense",
    channel: "Parceiro",
  },
];
